ALTER TABLE students
  ADD COLUMN IF NOT EXISTS gender VARCHAR(20),
  ADD COLUMN IF NOT EXISTS age INTEGER,
  ADD COLUMN IF NOT EXISTS residence_location VARCHAR(255),
  ADD COLUMN IF NOT EXISTS education_level VARCHAR(30),
  ADD COLUMN IF NOT EXISTS profession_area VARCHAR(255),
  ADD COLUMN IF NOT EXISTS education_institution VARCHAR(255),
  ADD COLUMN IF NOT EXISTS currently_employed BOOLEAN,
  ADD COLUMN IF NOT EXISTS job_type VARCHAR(30),
  ADD COLUMN IF NOT EXISTS current_position VARCHAR(255),
  ADD COLUMN IF NOT EXISTS industry_sector VARCHAR(255),
  ADD COLUMN IF NOT EXISTS years_experience INTEGER,
  ADD COLUMN IF NOT EXISTS time_in_current_position VARCHAR(100);
