-- Catálogo completo STPS: áreas temáticas del curso (178 entradas)
INSERT INTO stps_thematic_areas (code, name) VALUES
  ('1000', 'Producción'),
  ('1100', 'Producción general'),
  ('1110', 'Producción agrícola'),
  ('1111', 'Operador de maquinaria agrícola'),
  ('1112', 'Fruticultura'),
  ('1113', 'Horticultura'),
  ('1114', 'Floricultura'),
  ('1120', 'Producción pecuaria'),
  ('1121', 'Inseminación artificial'),
  ('1122', 'Avicultura'),
  ('1123', 'Cunicultura'),
  ('1124', 'Apicultura'),
  ('1130', 'Silvicultura'),
  ('1140', 'Producción pesquera'),
  ('1141', 'Acuacultura'),
  ('1210', 'Producción minera'),
  ('1220', 'Extracción de petróleo y gas natural'),
  ('1300', 'Producción industrial'),
  ('1311', 'Preparación y conservación de alimentos'),
  ('1312', 'Elaboración de refrescos, cervezas y bebidas alcohólicas'),
  ('1313', 'Tratamiento de agua'),
  ('1314', 'Beneficio y fabricación de productos del tabaco'),
  ('1321', 'Industria textil'),
  ('1322', 'Prendas de vestir'),
  ('1323', 'Artículos de cuero y sus productos'),
  ('1324', 'Tapicería'),
  ('1331', 'Operación de aserraderos'),
  ('1332', 'Fabricación de muebles y accesorios de madera'),
  ('1333', 'Fabricación de envases y otros artículos de madera'),
  ('1341', 'Fabricación de pasta de celulosa, papel, cartón y sus derivados'),
  ('1342', 'Edición'),
  ('1343', 'Industria editorial y grafica'),
  ('1351', 'Procesamiento de petróleo y petroquímica básica'),
  ('1352', 'Procesamiento de químicos en general'),
  ('1353', 'Procesamiento químico farmacéutico'),
  ('1354', 'Fabricación y regeneración de productos de hule'),
  ('1355', 'Fabricación de productos de plástico'),
  ('1361', 'Vidrio, alfarería y cerámica no artesanal'),
  ('1371', 'Fundición'),
  ('1381', 'Soldadura y pailería'),
  ('1382', 'Operación de maquinas herramienta'),
  ('1383', 'Diseño industrial y estructural'),
  ('1391', 'Acabados industriales'),
  ('1392', 'Relojería y joyería'),
  ('1393', 'Artesanías y manualidades'),
  ('1400', 'Construcción en general'),
  ('1401', 'Albañilería'),
  ('1402', 'Herrería'),
  ('1403', 'Azulejería'),
  ('1404', 'Diseño arquitectónico'),
  ('1405', 'Plomería y fontanería'),
  ('1407', 'Pintura'),
  ('1408', 'Tapicería de paredes'),
  ('1409', 'Maquinaria para construcción'),
  ('1500', 'Electricidad general'),
  ('1501', 'Electromecánica'),
  ('1502', 'Electrónica'),
  ('2000', 'Servicios'),
  ('2100', 'Turismo'),
  ('2101', 'Hotelería'),
  ('2102', 'Restaurantes'),
  ('2103', 'Guía de turistas'),
  ('2201', 'Conducción de vehículos'),
  ('2301', 'Almacenista e inventarios'),
  ('2501', 'Servicios financieros'),
  ('2502', 'Servicios bancarios'),
  ('2503', 'Seguros'),
  ('2600', 'Educación'),
  ('2601', 'Idiomas'),
  ('2602', 'Métodos pedagógicos y medios de enseñanza'),
  ('2603', 'Formación y actualización docente'),
  ('2604', 'Actualización de programas educativos'),
  ('2605', 'Materias formativas y tecnológicas'),
  ('2700', 'Salud'),
  ('2701', 'Cursos de capacitacion dirigidos a paramédicos y enfermeras'),
  ('2703', 'Prótesis'),
  ('2704', 'Terapias'),
  ('2706', 'Salud animal'),
  ('2900', 'Servicios de belleza'),
  ('3000', 'Administración, contabilidad y economía'),
  ('3110', 'Administración general'),
  ('3111', 'Administración de empresas agropecuarias, forestales o pesqueras'),
  ('3112', 'Administración de empresas industriales'),
  ('3113', 'Administración de empresas comerciales'),
  ('3114', 'Administración de empresas turísticas'),
  ('3115', 'Administración de empresas de servicios'),
  ('3116', 'Administración publica'),
  ('3121', 'Apoyo a la operación administrativa'),
  ('3122', 'Auxiliar administrativo'),
  ('3123', 'Archivo'),
  ('3124', 'Apoyo secretarial'),
  ('3125', 'Auxiliar de crédito y cobranza'),
  ('3126', 'Otros apoyos'),
  ('3130', 'Formación empresarial y gerencial'),
  ('3131', 'Apoyo a la calidad'),
  ('3132', 'Recursos humanos'),
  ('3133', 'Formación y actualización de instructores'),
  ('3134', 'Administración de la capacitación y adiestramiento de personal'),
  ('3135', 'Relaciones laborales'),
  ('3136', 'Monitoreo y supervisión'),
  ('3137', 'Productividad y competitividad'),
  ('3138', 'Dirección y gestión'),
  ('3139', 'Planeación'),
  ('3140', 'Jurídico'),
  ('3141', 'Derecho laboral'),
  ('3142', 'Derecho mercantil'),
  ('3143', 'Derecho fiscal'),
  ('3144', 'Derecho penal'),
  ('3145', 'Derecho en general'),
  ('3146', 'Derecho internacional'),
  ('3147', 'Marcas y patentes'),
  ('148', 'Peritaje y evaluación'),
  ('3200', 'Contabilidad general y auditoria'),
  ('3201', 'Contabilidad de costos'),
  ('3202', 'Contabilidad fiscal'),
  ('3203', 'Contabilidad financiera'),
  ('3204', 'Contabilidad pública'),
  ('3205', 'Auditoria'),
  ('3300', 'Economía general'),
  ('4000', 'Comercialización'),
  ('4100', 'Mercadotecnia'),
  ('4200', 'Promoción y publicidad'),
  ('4300', 'Ventas y distribución'),
  ('4400', 'Comercio internacional y aduanas'),
  ('5000', 'Mantenimiento y reparación'),
  ('5101', 'Mantenimiento y reparación de maquinas y equipo agropecuario y pesca'),
  ('5102', 'Mantenimiento y reparación de maquinaria y equipo industrial'),
  ('5103', 'Mantenimiento, reparación y soporte técnico de equipo de cómputo'),
  ('5104', 'Mantenimiento y reparación de equipo especializado'),
  ('5105', 'Mantenimiento y reparación de equipo de comunicación'),
  ('5201', 'Mantenimiento y reparación de automóviles, autobuses y camiones'),
  ('5202', 'Mantenimiento y reparación de aeronaves'),
  ('5203', 'Mantenimiento y reparación de transportes marítimos'),
  ('5205', 'Mantenimiento y reparación de equipo ferroviario'),
  ('5300', 'Mantenimiento y reparación de electrodomésticos'),
  ('5301', 'Mantenimiento y reparación de equipos eléctricos'),
  ('5400', 'Servicios'),
  ('5401', 'De limpieza industrial y domestica'),
  ('5402', 'Personales'),
  ('5403', 'Inmobiliarios'),
  ('5404', 'Consultorías'),
  ('5405', 'Ambientales'),
  ('5406', 'Funerarios'),
  ('5407', 'Investigación en general'),
  ('5500', 'Control de plagas en campo, industria y hogares'),
  ('6000', 'Seguridad'),
  ('6100', 'Seguridad industrial'),
  ('6200', 'Seguridad bancaria'),
  ('6300', 'Seguridad publica'),
  ('6400', 'Higiene y seguridad en el trabajo'),
  ('7000', 'Desarrollo personal y familiar'),
  ('7100', 'Relaciones humanas'),
  ('7200', 'Actividades culturales y artísticas'),
  ('7300', 'Actividades deportivas'),
  ('7400', 'Relaciones familiares'),
  ('8000', 'Uso de tecnologías de la información y comunicación'),
  ('8100', 'Programación de computadoras'),
  ('8101', 'Paquetería de computo'),
  ('8102', 'Bases de datos'),
  ('8103', 'Computación en general'),
  ('8200', 'Correo'),
  ('8201', 'Mensajería y paquetería especializada'),
  ('8202', 'Telégrafos'),
  ('8203', 'Servicio telefónico'),
  ('8204', 'Radio'),
  ('8205', 'Televisión'),
  ('8206', 'Cinematografía'),
  ('8207', 'Fotografía'),
  ('8300', 'Telecomunicaciones'),
  ('8301', 'Técnicas de comunicación'),
  ('8302', 'Operación de equipos de comunicación en general'),
  ('8303', 'Productor de recursos para la comunicación'),
  ('9000', 'Participación social'),
  ('9100', 'Participación política'),
  ('9200', 'Organización comunitaria'),
  ('9300', 'Capacitacion sindical'),
  ('9400', 'Áreas diversas'),
  ('9500', 'No especificado')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
